site_name: Kingshot Guide
site_description: Strategy guide for Kingshot mobile game events
site_url: 
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - toc.integrate
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Overview: index.md
  - Events:
    - Hall of Governors:
      - Overview: events/halls-of-governors.md
      - 1st Hall of Governors: events/halls-of-governors/1st-hog.md
      - 2nd Hall of Governors: events/halls-of-governors/2nd-hog.md
      - 3rd Hall of Governors: events/halls-of-governors/3rd-hog.md
      - "4th & 5th Hall of Governors": events/halls-of-governors/4th-5th-hog.md
    - Strongest Governor: events/strongest-governor.md
    - Bear Hunt: events/bear-hunt.md
    - Swordland: events/swordland.md
    - Eternity's Reach: events/eternitys-reach.md
    - Viking Vengeance: events/viking-vengance.md
