site_name: Kingshot Guide
site_description: Strategy guide for Kingshot mobile game events
site_url: 
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - toc.integrate
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Overview: index.md
  - Events:
    - Hall of Governors:
      - Overview: events/halls-of-governors.md
      - 1st Hall of Governors: events/halls-of-governors/1st-hog.md
      - 2nd Hall of Governors: events/halls-of-governors/2nd-hog.md
      - 3rd Hall of Governors: events/halls-of-governors/3rd-hog.md
      - "4th & 5th Hall of Governors": events/halls-of-governors/4th-5th-hog.md
    - Strongest Governor: events/strongest-governor.md
    - Bear Hunt: events/bear-hunt.md
    - Swordland: events/swordland.md
    - Eternity's Reach: events/eternitys-reach.md
    - Viking Vengeance: events/viking-vengance.md
  - Heroes:
    - Heroes Index: heroes/index.md
    - Generation 3:
      - Jaeger: heroes/jaeger.md
      - Eric: heroes/eric.md
      - Petra: heroes/petra.md
    - Generation 2:
      - Hilde: heroes/hilde.md
      - Zoe: heroes/zoe.md
      - Marlin: heroes/marlin.md
    - Generation 1:
      - Jabel: heroes/jabel.md
      - Amadeus: heroes/amadeus.md
      - Helga: heroes/helga.md
      - Saul: heroes/saul.md
    - Epic:
      - Yeonwoo: heroes/yeonwoo.md
      - Fahd: heroes/fahd.md
      - Chenko: heroes/chenko.md
      - Gordon: heroes/gordon.md
      - Diana: heroes/diana.md
      - Howard: heroes/howard.md
      - Quinn: heroes/quinn.md
    - Rare:
      - Olive: heroes/olive.md
      - Edwin: heroes/edwin.md
      - Seth: heroes/seth.md
      - Forrest: heroes/forrest.md
